data:
  corpus_1:
    path_src: dataset/USPTO_full_PtoTMPtoR_aug10/train/tmp_product.txt
    path_tgt: dataset/USPTO_full_PtoTMPtoR_aug10/train/tmp_reactant.txt
    weight: 1.0
  valid:
    path_src: dataset/USPTO_full_PtoTMPtoR_aug10/val/tmp_product.txt
    path_tgt: dataset/USPTO_full_PtoTMPtoR_aug10/val/tmp_reactant.txt

n_sample: 0
save_data: dataset/USPTO_full_PtoTMPtoR_aug10/example
src_vocab: dataset/USPTO_full_PtoTMPtoR_aug10/example.tmp_vocab.src
tgt_vocab: dataset/USPTO_full_PtoTMPtoR_aug10/example.tmp_vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

save_model: models/USPTO_FULL_TMPtoR_aug10/model.product-reactants
save_checkpoint_steps: 10000
keep_checkpoint: 40
seed: 3435
train_steps: 600000
valid_steps: 50000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 192
valid_batch_size: 192
batch_type: sents
normalization: sents
dropout: 0.3
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: true
position_encoding: true
max_relative_positions: 8

world_size: 4
gpu_ranks:
- 0
- 1
- 2
- 3

