data:
  corpus_1:
    path_src: dataset/USPTO_50K_P2S2R_aug20/S2R/train/src-train.txt
    path_tgt: dataset/USPTO_50K_P2S2R_aug20/S2R/train/tgt-train.txt
  valid:
    path_src: dataset/USPTO_50K_P2S2R_aug20/S2R/val/src-val.txt
    path_tgt: dataset/USPTO_50K_P2S2R_aug20/S2R/val/tgt-val.txt

n_sample: 0
save_data: dataset/USPTO_50K_P2S2R_aug20/S2R/example
src_vocab: dataset/USPTO_50K_P2S2R_aug20/S2R/example.vocab.src
tgt_vocab: dataset/USPTO_50K_P2S2R_aug20/S2R/example.vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

save_model: exp/USPTO_50K_P2S2R_aug20/S2R/model.synthons-reactants
save_checkpoint_steps: 10000
keep_checkpoint: 40
seed: 3435
train_steps: 1500000
valid_steps: 50000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 64
valid_batch_size: 64
batch_type: sents
normalization: sents
dropout: 0.1
attention_dropout: 0.1
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0
