model: models/PtoR/USPTO_50K_PtoR.pt
src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoTMPtoR_aug20/test/tmp_product-mini.txt
# src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/test/tgt-test.txt
output: sample/cross_dataset_weight_OOD_inference/finetune_oriP2R_model_on_TMP_product.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

