data:
  corpus_1:
    path_src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/train/src-train.txt
    path_tgt: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/train/tgt-train.txt
  valid:
    path_src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/val/src-val.txt
    path_tgt: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/val/tgt-val.txt

n_sample: 0
save_data: dataset/USPTO_full_pretrain_aug5_masked_token/example
src_vocab: dataset/USPTO_full_pretrain_aug5_masked_token/example.vocab.src
tgt_vocab: dataset/USPTO_full_pretrain_aug5_masked_token/example.vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'False'

train_from: /root/retro_synthesis/root_align_retro/models/pretrained/reactant_pretrained.pt
reset_optim: 'all'
save_model: /root/retro_synthesis/root_align_retro/models/PtoR_retrain/finetune_model.p2r_retrain
save_checkpoint_steps: 10000
keep_checkpoint: 40
seed: 3435
train_steps: 300000
valid_steps: 50000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 128
valid_batch_size: 128
batch_type: sents
normalization: sents
dropout: 0.1
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 2
gpu_ranks:
- 0
- 1

# 日志监控
log_file: /root/retro_synthesis/root_align_retro/logs/P2R-finetune_retrain.log
tensorboard: True
tensorboard_log_dir: /root/retro_synthesis/root_align_retro/tensorboard/P2R-finetune
