# model: exp/USPTO_50K_PtoR_aug20/average_model_56-60.pt
# src: dataset/USPTO_50K_PtoR_aug20/test/src-test.txt
# output: exp/USPTO_50K_PtoR_aug20/average_model_56-60-results.txt
model: models/USPTO_50K_PtoR_aug20_rope_pos/finetune_average_model_36-40.pt
src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoR_aug20/test/src-test_mini.txt
output: sample/retrain_USPTO_50K_PtoR_aug20/USPTO_50K_PtoR_rope_36-40.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 16392
batch_type: tokens
max_length: 500
seed: 0

