model: models/USPTO_FULL_TMPtoR_fromUSPTO-MIT_TMP2R_aug10/finetune_model.product-template_step_140000.pt
src: /root/reaction_data/pretrain_aug/USPTO_FULL_PtoTMPtoR_aug10/test/tmp_product.txt
output: sample/USPTO_FULL_PtoTMPtoR_fromUSPTOFULLP2R_aug10/finetune_model_14.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

