model: models/TMPtoR_fromUSPTO50K_P2R_aug20_Moe_cls1/finetune_average_model_26-30.pt
src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoTMPtoR_aug20/test/cls/cls_10/tmp_product.txt
output: sample/USPTO_50K_TMPtoR_fromUSPTO50KP2R_aug20/Moe_cls/finetune_average_model_26-30_Moe1_cls_10.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 16384
batch_type: tokens
max_length: 500
seed: 0

