# model: models/TMPtoR_fromUSPTO-FULL_TMP2R_aug10/finetune_average_model_26-30.pt
model: models/TMPtoR_fromUSPTO50K_P2R_aug20_Moe_cls1/finetune_average_model_26-30.pt
src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoTMPtoR_aug20/test/cls/cls_10/tmp_product.txt
output: sample/USPTO_50K_TMPtoR_fromUSPTO50KP2R_aug20/Moe_cls/finetune_average_model_26-30_Moe1_cls_10.txt
log_file: sample/USPTO_50K_TMPtoR_fromUSPTO50KP2R_aug20/Moe_cls/finetune_average_model_26-30_Moe1_cls_10.log
gpu: 0
beam_size: 10
n_best: 10
ban_unk_token: True
batch_size: 16384
batch_type: tokens
max_length: 200
seed: 0

# CUDA_VISIBLE_DEVICES=0 onmt_translate -config /root/retro_synthesis/root_align_retro/pretrain_finetune/finetune/PtoTMPtoR/TMPtoR-MIT-aug10-translate.yml