model: /root/retro_synthesis/root_align_retro/models/PtoS/USPTO_50K_PtoS.pt
src: /root/retro_synthesis/root_align_retro/dataset/USPTO_50K_PtoTMPtoR_aug20/test/tmp_product-mini.txt
output: sample/USPTO_50K_TMPtoR_aug20/finetune_average_model_USPTO_50K_PtoS.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

