model: /root/retro_synthesis/root_align_retro/models/USPTO_MIT_TMPtoR_fromUSPTO-MIT_TMP2R_aug10/finetune_average_model_86-90.pt
src: /root/reaction_data/pretrain_aug/USPTO_MIT_PtoTMPtoR_aug10/test/tmp_product.txt
output: sample/USPTO_MIT_PtoTMPtoR_fromUSPTOMITP2R_aug10/finetune_model_86-90.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

