
model: models/TMPtoR_jump3_fromUSPTO_MIT_P2R_aug5_expand-ring/finetune_average_model_26-30.pt
src: /root/reaction_data/pretrain_aug/USPTO_MIT_PtoTMPtoR_aug10/test/tmp_product_jump3_aug5_enhance_ring_mini.txt
output: sample/USPTO_MIT_TMPtoR_jump3_fromUSPTO_MIT_P2R_aug5_expand/finetune_average_model_26-30.txt
log_file: sample/USPTO_MIT_TMPtoR_jump3_fromUSPTO_MIT_P2R_aug5_expand/finetune_average_model_26-30.log
gpu: 0
beam_size: 10
n_best: 10
ban_unk_token: True
batch_size: 16384
batch_type: tokens
max_length: 200
seed: 0

# CUDA_VISIBLE_DEVICES=0 onmt_translate -config pretrain_finetune/finetune/PtoTMPtoR/TMPtoR-MIT-aug10-translate.yml