model: /root/retro_synthesis/root_align_retro/models/USPTO50K_TMPtoR_jump10_from_scratch_aug10/model.product-template_step_200000.pt
src: /root/reaction_data/pretrain_aug/USPTO_50K_PtoTMPtoR_aug20/test/tmp_product_jump10_aug10.txt
output: sample/radius_search/USPTO_50K_TMPtoR_jump10_from_scratch_aug10/finetune_model_20.txt
log_file: sample/radius_search/USPTO_50K_TMPtoR_jump10_from_scratch_aug10/finetune_model_20.log
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0

# CUDA_VISIBLE_DEVICES=1 onmt_translate -config /root/retro_synthesis/root_align_retro/pretrain_finetune/finetune/PtoTMPtoR/TMPtoR-50K-aug20-translate.yml
